ForoIA/Models/Db/QuestionType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ForoIA.Models.Db {

    public class QuestionType {

        public int Id { get; set; }

        [Required]
        public string Description { get; set; }

    }

}

ForoIA/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ForoIA.Models.Db;
using ForoIA.ViewModel.Post;

namespace ForoIA.Controllers {

    public class PostsController : Controller {

        private ForoDbContext db = new ForoDbContext();

        // GET: Posts
        public ActionResult Index() {

            var post = db.Post
                         .Include(p => p.Category)
                         .OrderByDescending(p => p.Date);

            return View(post.ToList());

        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Post post = db.Post.Find(id);
            db.Entry(post).Collection(p => p.Commments).Load();

            if (post == null) {
                return HttpNotFound();
            }

            if (TempData["ModelState"] != null && !ModelState.Equals(TempData["ModelState"]))
                ModelState.Merge((ModelStateDictionary)TempData["ModelState"]);

            return View(post);

        }

        // GET: Post/Category/id
        public ActionResult Category(int id) {

            Category category = db.Category.Find(id);

            if (category == null) {
                return HttpNotFound();
            }

            var posts = db.Post
                          .Include(p => p.Category)
                          .Where(p => p.CategoryId == id)
                          .Take(5)
                          .ToList();

            return View("Index", posts);

        }

        // GET: Posts/User/userName
        public ActionResult UserPosts(string userName) {

            if (string.IsNullOrWhiteSpace(userName)) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var viewModel = db.Post
                              .Where(p => p.UserName.Equals(userName))
                              .ToList();

            return View("Index", viewModel);

        }

        // It could be <<User>> not <<PartialUserPosts>>
        // GET: Posts/User/
        [Authorize]
        [ChildActionOnly]
        public PartialViewResult PartialUserPosts() {

            var userName = User.Identity.Name;

            var viewModel = db.Post
                              .Where(p => p.UserName.Equals(userName))
                              .Select(p => new UserPostsViewModel() {

                                  Id = p.Id,
                                  Title = p.Title,
                                  Category = p.Category.Name,
                                  Date = p.Date

                              })
                              .ToList();

            return PartialView("_UserPosts", viewModel);

        }

        // GET: Posts/Create
        public ActionResult Create() {

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");

            return View();

        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,CategoryId,Review,Content")] CreatePostViewModel viewModel) {

            if (ModelState.IsValid) {

                var post = new Post() {

                    Title = viewModel.Title,
                    CategoryId = viewModel.CategoryId,
                    Review = viewModel.Review,
                    Content = viewModel.Content,
                    UserName = User.Identity.Name,
                    Date = DateTime.Now,

                };

                db.Post.Add(post);

                db.SaveChanges();

                return RedirectToAction("Index");

            }

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", viewModel.CategoryId);

            return View(viewModel);

        }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Post post = db.Post.Find(id);

            if (post == null) {
                return HttpNotFound();
            }

            var viewModel = new EditPostViewModel() {

                Id = post.Id,
                Title = post.Title,
                Review = post.Review,
                CategoryId = post.CategoryId,
                Content = post.Content

            };

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", viewModel.CategoryId);

            return View(viewModel);

        }

        // POST: Posts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,CategoryId,Review,Content")] EditPostViewModel viewModel) {

            if (ModelState.IsValid) {

                var post = db.Post.Find(viewModel.Id);

                post.Title = viewModel.Title;
                post.CategoryId = viewModel.CategoryId;
                post.Review = viewModel.Review;
                post.Content = viewModel.Content;

                db.Entry(post).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");

            }

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", viewModel.CategoryId);

            return View(viewModel);

        }

        // GET: Posts/Delete/5
        public ActionResult Delete(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var viewModel = db.Post
                              .Where(p => p.UserName.Equals(User.Identity.Name) && p.Id == id)
                              .Select(p => new UserPostsViewModel() {

                                  Id = p.Id,
                                  Title = p.Title,
                                  Category = p.Category.Name,
                                  Date = p.Date

                              })
                              .FirstOrDefault();

            if (viewModel == null) {
                return HttpNotFound();
            }

            return View(viewModel);

        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {

            Post post = db.Post.Find(id);

            db.Post.Remove(post);

            db.SaveChanges();

            return RedirectToAction("Index");

        }

        // POST: Posts/Search/param
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(string param) {

            var viewModel = db.Post
                              .Where(p =>
                                          p.Title.Contains(param) ||
                                          p.Review.Contains(param) ||
                                          p.Content.Contains(param) ||
                                          p.UserName.Contains(param)
                                          );


            return View("Index", viewModel);

        }

        protected override void Dispose(bool disposing) {

            if (disposing) {
                db.Dispose();
            }

            base.Dispose(disposing);

        }

    }

}

ForoIA/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ForoIA.Models.Db;
using ForoIA.ViewModel.Test;
using System.Diagnostics;
using System.Text;

namespace ForoIA.Controllers {

    [Authorize]
    public class TestsController : Controller {

        private ForoDbContext db = new ForoDbContext();

        // GET: Tests
        public ActionResult Index() {

            return View();

        }

        // GET: Tests/ConfigurarPrueba
        public ActionResult ConfigurarPrueba() {

            // Se valida si el usuario ya cuenta con un examen en progreso
            var configTest = db.ConfigurationTest.FirstOrDefault(c => c.Username.Equals(User.Identity.Name));

            // Si no es null, ya hay examen
            if (configTest != null) {

                // Se obtiene la pregunta
                var siguientePregunta = db.TestAnswer
                                        .Include(ta => ta.Test)
                                        .Where(ta => ta.ConfigurationTestId == configTest.Id && ta.IsAnswered == false)
                                        .AsEnumerable()
                                        .Select(ta => new QuestionViewModel() {

                                            Id = ta.Id,
                                            Question = ta.Test.Question,
                                            QuestionType = ta.Test.QuestionTypeId,
                                            Answers = ta.Test.Answers.ToList().Select(a => new KeyValuePair<int, string>(a.Id, a.Description))

                                        })
                                        .FirstOrDefault();

                // Si no es null, aún hay preguntas por responder
                if (siguientePregunta != null) {

                    return View("Question", siguientePregunta);

                }

                return RedirectToAction("PruebaFinalizada");

            }

            return View();

        }

        // POST: Tests/ConfigurarPrueba
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfigurarPrueba(ConfigurationTestViewModel config) {

            // Se obtienen las unidades seleccionadas
            List<int> unidades = new List<int>() {
                config.Unidad1 ? 1 : 0,
                config.Unidad2 ? 2 : 0,
                config.Unidad3 ? 3 : 0,
                config.Unidad4 ? 4 : 0,
                config.Unidad5 ? 5 : 0
            };


            if (unidades.All(u => u == 0)) {

                ModelState.AddModelError("unidades", "Se debe seleccionar al menos una unidad para ser evaluado.");

                return View();

            }

            // Se obtiene la dificultad seleccionada
            var dificultad = config.Dificultad;

            if (dificultad <= 0) {

                ModelState.AddModelError("dificultad", "Se debe seleccionar la dificultad con la que se evaluará.");

                return View();

            }

            // Se crea el registro de la configuración del test
            var configuration = new ConfigurationTest() {

                DificultyId = config.Dificultad,
                StartDate = DateTime.Now,
                Username = User.Identity.Name,
                Dificulty = db.Dificulty.First(d => d.Id == config.Dificultad)

            };

            // Se inserta el registro en la BD
            db.ConfigurationTest.Add(configuration);
            db.SaveChanges();

            List<TestAnswer> preguntas = new List<TestAnswer>();

            List<Test> preguntasObtenidas = null;

            // Obtener las preguntas aleatorias de acuerdo a los topicos seleccionados y la dificultad
            // Se seleccionarán 6 preguntas por cada tópico
            foreach (var topic in unidades) {

                // Con dificultad: Facil, Medio y Dificil

                if (dificultad < 4) {

                    // Se obtienen las preguntas de forma aleatoria
                    // dependiendo de la dificultad y de las unidades seleccionadas
                    preguntasObtenidas = db.Test.Include(t => t.Answers)
                                           .OrderBy(t => Guid.NewGuid())
                                           .Where(t => t.TopicId == topic && t.DificultId == dificultad)
                                           .Take(6)
                                           .ToList();

                } else { // Con dificultad de un poco de todo

                    // Se obtienen las preguntas de forma aleatoria
                    // dependiendo de la dificultad y de las unidades seleccionadas
                    preguntasObtenidas = db.Test.Include(t => t.Answers)
                                           .OrderBy(t => Guid.NewGuid())
                                           .Where(t => t.TopicId == topic)
                                           .Take(6)
                                           .ToList();

                }

                // De las preguntas obtenidas, se "meapean" ciertas propiedades al modelo TestAnswer
                foreach (var test in preguntasObtenidas) {

                    var testAnswer = new TestAnswer() {

                        ConfigurationTestId = configuration.Id,
                        TestId = test.Id,

                    };

                    preguntas.Add(testAnswer);

                }

            }

            // Se realiza el registro en la BD
            db.TestAnswer.AddRange(preguntas);
            db.SaveChanges();

            return RedirectToAction("IniciarPrueba");

        }

        // GET: Tests/IniciarPrueba
        public ActionResult IniciarPrueba() {

            // Se obtiene el nombre del usuaario
            var userName = User.Identity.Name;

            // Obtenemos la configuracion del usuario
            var testConfiguration = db.ConfigurationTest
                                      .First(t => t.Username.Equals(userName));

            // Se obtiene la primera pregunta
            var primeraPregunta = db.TestAnswer
                                    .Include(ta => ta.Test)
                                    .Where(ta => ta.ConfigurationTestId == testConfiguration.Id)
                                    .AsEnumerable()
                                    .Select(ta => new QuestionViewModel() {

                                        Id = ta.Id,
                                        Question = ta.Test.Question,
                                        QuestionType = ta.Test.QuestionTypeId,
                                        Answers = ta.Test.Answers.ToList().Select(a => new KeyValuePair<int, string>(a.Id, a.Description))

                                    })
                                    .First();

            return View("Question", primeraPregunta);

        }

        // POST: Tests/Siguiente/{AnswerId}/{AnswerText}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Siguiente(int AnswerId, string AnswerText) {

            // Se obtiene el nombre del usuaario
            var userName = User.Identity.Name;

            // Se cobtiene el la configuracion del Test del usuario
            var configTest = db.ConfigurationTest.First(c => c.Username.Equals(userName));

            // Se obtiene el registro de la pregunta que se ha respondido
            var testAnswer = db.TestAnswer.First(ta => ta.ConfigurationTestId == configTest.Id && ta.IsAnswered == false);

            // Se actualizan los campos
            testAnswer.AnwserIdSelected = AnswerId;
            testAnswer.IsAnswered = true;
            testAnswer.TextAnswer = AnswerText;

            // Se guardan los cambios en la BD
            db.Entry(testAnswer).State = EntityState.Modified;
            db.SaveChanges();

            // Se obtiene la siguiente pregunta
            var siguientePregunta = db.TestAnswer
                                    .Include(ta => ta.Test)
                                    .Where(ta => ta.ConfigurationTestId == configTest.Id && ta.IsAnswered == false)
                                    .AsEnumerable()
                                    .Select(ta => new QuestionViewModel() {

                                        Id = ta.Id,
                                        Question = ta.Test.Question,
                                        QuestionType = ta.Test.QuestionTypeId,
                                        Answers = ta.Test.Answers.ToList().Select(a => new KeyValuePair<int, string>(a.Id, a.Description))

                                    })
                                    .FirstOrDefault();

            ModelState.Clear();

            // Aun hay preguntas por responder
            if (siguientePregunta != null) {

                return View("Question", siguientePregunta);

            }

            return RedirectToAction("PruebaFinalizada");

        }

        public ActionResult PruebaFinalizada() {

            var userName = User.Identity.Name;

            // Se obtiene la configuración y las respuestas del test
            var configTest = db.ConfigurationTest
                               .Include(c => c.TestAnswer)
                               .FirstOrDefault(c => c.Username.Equals(userName));

            // Se obtienen los Id's de las respuestas cerradas constestadas
            var answersIdSelected = configTest.TestAnswer
                                              .Select(ta => ta.AnwserIdSelected)
                                              .ToList();

            // Se obtienen las respuestas
            var answers = db.Answer
                            .Where(a => answersIdSelected.Contains(a.Id))
                            .ToList();

            // Se cuentan las respuestas correctas
            var correctas = answers.Count(a => a.IsCorrect == true);

ForoIA/Views/Tests/ConfigurarPrueba.cshtml
@model ForoIA.ViewModel.Test.ConfigurationTestViewModel

@{
    ViewBag.Title = "ConfigurarPrueba";
    Layout = "~/Views/Tests/_Layout.cshtml";
}

<br />

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Configura tu prueba</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm()) {

            @Html.AntiForgeryToken()

            @Html.ValidationSummary(false, null, new { @class = "text-danger"})

            <div class="col-md-6">

                <h5>Selecciona las unidades con las que quieres ser evaluado.</h5>
                <br />

                <div class="input-group">
                    <span class="input-group-addon">
                        @Html.CheckBoxFor(m => m.Unidad1)
                    </span>
                    @Html.LabelFor(m => m.Unidad1, new { @class = "form-control" })
                </div>
                <br />

                <div class="input-group">
                    <span class="input-group-addon">
                        @Html.CheckBoxFor(m => m.Unidad2)
                    </span>
                    @Html.LabelFor(m => m.Unidad2, new { @class = "form-control" })
                </div>
                <br />

                <div class="input-group">
                    <span class="input-group-addon">
                        @Html.CheckBoxFor(m => m.Unidad3)
                    </span>
                    @Html.LabelFor(m => m.Unidad3, new { @class = "form-control" })
                </div>
                <br />

                <div class="input-group">
                    <span class="input-group-addon">
                        @Html.CheckBoxFor(m => m.Unidad4)
                    </span>
                    @Html.LabelFor(m => m.Unidad4, new { @class = "form-control" })
                </div>
                <br />

                <div class="input-group">
                    <span class="input-group-addon">
                        @Html.CheckBoxFor(m => m.Unidad5)
                    </span>
                    @Html.LabelFor(m => m.Unidad5, new { @class = "form-control" })
                </div>
                <br />

            </div>

            <div class="col-md-6">

                <h5>Selecciona la dificultad con la que quieres ser evaluado.</h5>
                <br />

                <div id="radio">

                    <div class="input-group">
                        <span class="input-group-addon">
                            @Html.RadioButtonFor(m => m.Dificultad, "1", new { id = "Facil" })
                        </span>
                        @Html.Label("Facil", "Facil", new { @class = "form-control" })
                    </div>
                    <br />

                    <div class="input-group">
                        <span class="input-group-addon">
                            @Html.RadioButtonFor(m => m.Dificultad, "2", new { id = "Medio" })
                        </span>
                        @Html.Label("Medio", "Medio", new { @class = "form-control" })
                    </div>
                    <br />

                    <div class="input-group">
                        <span class="input-group-addon">
                            @Html.RadioButtonFor(m => m.Dificultad, "3", new { id = "Dificil" })
                        </span>
                        @Html.Label("Dificil", "Dificil", new { @class = "form-control" })
                    </div>
                    <br />

                    <div class="input-group">
                        <span class="input-group-addon">
                            @Html.RadioButtonFor(m => m.Dificultad, "4", new { id = "UnPocoDeTodo" })
                        </span>
                        @Html.Label("UnPocoDeTodo", "Un poco de todo", new { @class = "form-control" })
                    </div>
                    <br />

                </div>

                <button class="pull-right btn btn-default" type="submit">Confirmar y comenzar la prueba</button>

            </div>
        }
    </div>
</div>

ForoIA/Views/Tests/Create.cshtml
@model ForoIA.Models.Db.Test

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Test</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DificultId, "DificultId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DificultId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DificultId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuestionTypeId, "QuestionTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("QuestionTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QuestionTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ForoIA/Views/Tests/Index.cshtml
@model IEnumerable<ForoIA.Models.Db.Test>

@{
    ViewBag.Title = "Prueba";
    Layout = "_Layout.cshtml";
}

<br />

<div class="jumbotron">
    <h1>Bienvenido a la sección de pruebas en linea</h1>
    <p>Aquí pondrás a prueba y demostrarás tus conocimientos sobre la Inteligencia Artificial.</p>
    <p>Las preguntas están relacionadas al temario aplicado en la Escuela Superior de Ingeniería Mecánica y Electrica Unidad Culhuacan y a los documentos proporcionados en la página.</p>
    <p>Solo se realiza UNA SOLA VEZ la prueba, para realizar otra prueba, contacte con el Administrador :).</p>
    @*<p><a class="btn btn-primary btn-lg" href="#" role="button">Empezar</a></p>*@
    @*@Ajax.ActionLink("Empezar prueba", "ConfigurarPrueba", "Tests", null, new AjaxOptions() {
                                                                                            HttpMethod = "GET",
                                                                                            InsertionMode = InsertionMode.Replace,
                                                                                            UpdateTargetId = "renderBody" }, 
                                                                       new { @class = "btn btn-primary btn-lg" })*@
    @Html.ActionLink("Empezar prueba", "ConfigurarPrueba", "Tests", null, new { @class = "btn btn-primary btn-lg"})
</div>



@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Dificult.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuestionType.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Question)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Dificult.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionType.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Question)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

    </table>*@

ForoIA/Views/Tests/PruebaFinalizada.cshtml
@{
    ViewBag.Title = "Prueba Finalizada";
    Layout = "~/Views/Tests/_Layout.cshtml";
}

<h2>Prueba Finalizada</h2>

Tu calificación es: @ViewBag.Calificacion

ForoIA/Views/Tests/Question.cshtml
@model ForoIA.ViewModel.Test.QuestionViewModel

@{
    ViewBag.Title = "Question";
    Layout = "~/Views/Tests/_Layout.cshtml";
}

<br />

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Pregunta: @Model.Question</h3>
    </div>
    @using (Html.BeginForm("Siguiente", "Tests")) {

        @Html.AntiForgeryToken()

        <div class="panel-body">
            <div class="col-md-12">
                @if (Model.QuestionType == 1) {

                    @Html.HiddenFor(m => m.AnswerId, new { @Value = "0" })

                    foreach (var answer in Model.Answers) {
                        <br />
                        <div class="form-group">
                            @*@Html.TextArea("AnswerText", null, new { @class = "form-control", placeholder = "Ingresa tu respuesta"})*@
                            @Html.TextAreaFor(m => m.AnswerText, new { @class = "form-control" })
                        </div>

                    }

                } else {

                    foreach (var answer in Model.Answers) {
                        <br />
                        <div class="input-group">
                            <span class="input-group-addon">
                                @Html.RadioButtonFor(m => m.AnswerId, answer.Key, new { id = "k" + answer.Key.ToString() })
                            </span>
                            @Html.Label("k" + answer.Key.ToString(), answer.Value, new { @class = "form-control"})
                        </div>
                    }
                }
                <br />
            </div>
        </div>

        <div class="panel-footer">
            <button type="submit" class="btn btn-default">Siguiente</button>
        </div>

    }
</div>

ForoIA/Views/Tests/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IA</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inteligencia Artificial en la ESIME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Online Test", "Index", "Tests")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        <div id="renderBody">
            @RenderBody()
        </div>

        <!-- /.row -->
        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Inteligencia Artificial en la ESIME @DateTime.Now.Year</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

ForoIA/Views/Tests/_Question.cshtml
@model ForoIA.ViewModel.Test.QuestionViewModel

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">@Model.Question</h3>
    </div>
    @using (Ajax.BeginForm("", "Posts", new AjaxOptions() { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "renderBody"})) {

        @Html.AntiForgeryToken()

        <div class="panel-body">

            @foreach (var answer in Model.Answers) {

                @if (Model.QuestionType == 1) {

                    <div class="input-group">
                        <span class="input-group-addon">
                            @Html.RadioButtonFor(m => m.AnswerId, answer.Key, new { id = answer.Key.ToString() })
                        </span>
                        @Html.Label(answer.Key.ToString(), answer.Value, new { @class = "form-control" })
                    </div>

                } else {

                    @Html.TextAreaFor(m => m.AnswerText, new { @class = "" })

                }

            }

        </div>

        <div class="panel-footer">
            <button type="submit" class="btn btn-default">Siguiente</button>
        </div>

    }
</div>