ForoIA/Models/Db/Comment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ForoIA.Models.Db {

    public class Comment {

        public int Id { get; set; }

        public int PostId { get; set; }

        [Required]
        [StringLength(25)]
        public string UserName { get; set; }

        [Required]
        public DateTime CommentTime { get; set; }

        [Required]
        [StringLength(1024)]
        public string Content { get; set; }

        // Navigation Properties

        public virtual Post Post { get; set; }

    }

}

ForoIA/Models/Db/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ForoIA.Models.Db {

    public class Post {

        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        [StringLength(25)]
        public string UserName { get; set; }

        [Required]
        public DateTime Date { get; set; }

        public int CategoryId { get; set; }

        [Required]
        [StringLength(1024)]
        public string Review { get; set; }

        [Required]
        [StringLength(5120)]
        public string Content { get; set; }

        // Navigation Properties

        public virtual Category Category { get; set; }

        public virtual ICollection<Comment> Commments { get; set; }

    }

}

ForoIA/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ForoIA.Models.Db;

namespace ForoIA.Controllers {

    public class CommentsController : Controller {

        private ForoDbContext db = new ForoDbContext();

        // GET: Comments
        public ActionResult Index() {

            var comment = db.Comment.Include(c => c.Post);

            return View(comment.ToList());

        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Comment comment = db.Comment.Find(id);

            if (comment == null) {
                return HttpNotFound();
            }

            return View(comment);

        }

        // GET: Comments/PartialUserComments
        [Authorize]
        [ChildActionOnly]
        public PartialViewResult PartialUserPosts() {

            var userName = User.Identity.Name;

            var viewModel = db.Comment
                              .Include(c => c.Post)
                              .Where(p => p.UserName.Equals(userName))
                              .ToList();

            return PartialView("Index", viewModel);

        }

        // GET: Comments/Create
        public ActionResult Create() {

            ViewBag.PostId = new SelectList(db.Post, "Id", "Title");

            return View();

        }

        // POST: Comments/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,PostId,UserName,CommentTime,Content")] Comment comment) {

        //    if (ModelState.IsValid) {

        //        db.Comment.Add(comment);

        //        db.SaveChanges();

        //        return RedirectToAction("Index");

        //    }

        //    ViewBag.PostId = new SelectList(db.Post, "Id", "Title", comment.PostId);

        //    return View(comment);

        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string content, int ID, string userName) {

            if (!User.Identity.IsAuthenticated) {

                ModelState.AddModelError("indentity", "Debes de inciar sesión para dejar tu comentario.");

                TempData["ModelState"] = ModelState;

            } else if (string.IsNullOrWhiteSpace(content)) {

                ModelState.AddModelError("content", "El campo de comentarios no debe estar vacio.");

                TempData["ModelState"] = ModelState;

            } else {

                db.Comment.Add(new Models.Db.Comment() {

                    PostId = ID,
                    CommentTime = DateTime.Now,
                    UserName = userName,
                    Content = content

                });

                db.SaveChanges();

            }

            return RedirectToAction("Details", "Posts", new { id = ID });

        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Comment comment = db.Comment.Find(id);

            if (comment == null) {
                return HttpNotFound();
            }

            ViewBag.PostId = new SelectList(db.Post, "Id", "Title", comment.PostId);

            return View(comment);

        }

        // POST: Comments/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PostId,UserName,CommentTime,Content")] Comment comment) {

            if (ModelState.IsValid) {

                db.Entry(comment).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");

            }

            ViewBag.PostId = new SelectList(db.Post, "Id", "Title", comment.PostId);

            return View(comment);

        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Comment comment = db.Comment.Find(id);

            if (comment == null) {
                return HttpNotFound();
            }

            return View(comment);

        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {

            Comment comment = db.Comment.Find(id);

            db.Comment.Remove(comment);

            db.SaveChanges();

            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing) {

            if (disposing) {
                db.Dispose();
            }

            base.Dispose(disposing);

        }

    }

}

ForoIA/Controllers/MultimediaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ForoIA.Controllers {

    public class MultimediaController : Controller {

        [OutputCache(Duration = 120, Location = System.Web.UI.OutputCacheLocation.Client)]
        public ActionResult Index() {

            List<string> urls = new List<string>() {

                "https://www.youtube.com/embed/3IjP29wNAfE",
                "https://www.youtube.com/embed/eoIQmWd8LTQ",
                "https://www.youtube.com/embed/gCuPx9shWT0",
                "https://www.youtube.com/embed/cUeScCtTng4",
                "https://www.youtube.com/embed/qv6UVOQ0F44"

            };


            return View(urls);

        }

        public ActionResult Chapter(string fileName) {

            var fileStream = new FileStream(Server.MapPath(@"~/Files/" + fileName), FileMode.Open, FileAccess.Read);

            var fsResult = new FileStreamResult(fileStream, "application/pdf");

            return fsResult;

        }

    }

}

ForoIA/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ForoIA.Models.Db;
using ForoIA.ViewModel.Test;
using System.Diagnostics;
using System.Text;

namespace ForoIA.Controllers {

    [Authorize]
    public class TestsController : Controller {

        private ForoDbContext db = new ForoDbContext();

        // GET: Tests
        public ActionResult Index() {

            return View();

        }

        // GET: Tests/ConfigurarPrueba
        public ActionResult ConfigurarPrueba() {

            // Se valida si el usuario ya cuenta con un examen en progreso
            var configTest = db.ConfigurationTest.FirstOrDefault(c => c.Username.Equals(User.Identity.Name));

            // Si no es null, ya hay examen
            if (configTest != null) {

                // Se obtiene la pregunta
                var siguientePregunta = db.TestAnswer
                                        .Include(ta => ta.Test)
                                        .Where(ta => ta.ConfigurationTestId == configTest.Id && ta.IsAnswered == false)
                                        .AsEnumerable()
                                        .Select(ta => new QuestionViewModel() {

                                            Id = ta.Id,
                                            Question = ta.Test.Question,
                                            QuestionType = ta.Test.QuestionTypeId,
                                            Answers = ta.Test.Answers.ToList().Select(a => new KeyValuePair<int, string>(a.Id, a.Description))

                                        })
                                        .FirstOrDefault();

                // Si no es null, aún hay preguntas por responder
                if (siguientePregunta != null) {

                    return View("Question", siguientePregunta);

                }

                return RedirectToAction("PruebaFinalizada");

            }

            return View();

        }

        // POST: Tests/ConfigurarPrueba
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfigurarPrueba(ConfigurationTestViewModel config) {

            // Se obtienen las unidades seleccionadas
            List<int> unidades = new List<int>() {
                config.Unidad1 ? 1 : 0,
                config.Unidad2 ? 2 : 0,
                config.Unidad3 ? 3 : 0,
                config.Unidad4 ? 4 : 0,
                config.Unidad5 ? 5 : 0
            };


            if (unidades.All(u => u == 0)) {

                ModelState.AddModelError("unidades", "Se debe seleccionar al menos una unidad para ser evaluado.");

                return View();

            }

            // Se obtiene la dificultad seleccionada
            var dificultad = config.Dificultad;

            if (dificultad <= 0) {

                ModelState.AddModelError("dificultad", "Se debe seleccionar la dificultad con la que se evaluará.");

                return View();

            }

            // Se crea el registro de la configuración del test
            var configuration = new ConfigurationTest() {

                DificultyId = config.Dificultad,
                StartDate = DateTime.Now,
                Username = User.Identity.Name,
                Dificulty = db.Dificulty.First(d => d.Id == config.Dificultad)

            };

            // Se inserta el registro en la BD
            db.ConfigurationTest.Add(configuration);
            db.SaveChanges();

            List<TestAnswer> preguntas = new List<TestAnswer>();

            List<Test> preguntasObtenidas = null;

            // Obtener las preguntas aleatorias de acuerdo a los topicos seleccionados y la dificultad
            // Se seleccionarán 6 preguntas por cada tópico
            foreach (var topic in unidades) {

                // Con dificultad: Facil, Medio y Dificil

                if (dificultad < 4) {

                    // Se obtienen las preguntas de forma aleatoria
                    // dependiendo de la dificultad y de las unidades seleccionadas
                    preguntasObtenidas = db.Test.Include(t => t.Answers)
                                           .OrderBy(t => Guid.NewGuid())
                                           .Where(t => t.TopicId == topic && t.DificultId == dificultad)
                                           .Take(6)
                                           .ToList();

                } else { // Con dificultad de un poco de todo

                    // Se obtienen las preguntas de forma aleatoria
                    // dependiendo de la dificultad y de las unidades seleccionadas
                    preguntasObtenidas = db.Test.Include(t => t.Answers)
                                           .OrderBy(t => Guid.NewGuid())
                                           .Where(t => t.TopicId == topic)
                                           .Take(6)
                                           .ToList();

                }

                // De las preguntas obtenidas, se "meapean" ciertas propiedades al modelo TestAnswer
                foreach (var test in preguntasObtenidas) {

                    var testAnswer = new TestAnswer() {

                        ConfigurationTestId = configuration.Id,
                        TestId = test.Id,

                    };

                    preguntas.Add(testAnswer);

                }

            }

            // Se realiza el registro en la BD
            db.TestAnswer.AddRange(preguntas);
            db.SaveChanges();

            return RedirectToAction("IniciarPrueba");

        }

        // GET: Tests/IniciarPrueba
        public ActionResult IniciarPrueba() {

            // Se obtiene el nombre del usuaario
            var userName = User.Identity.Name;

            // Obtenemos la configuracion del usuario
            var testConfiguration = db.ConfigurationTest
                                      .First(t => t.Username.Equals(userName));

            // Se obtiene la primera pregunta
            var primeraPregunta = db.TestAnswer
                                    .Include(ta => ta.Test)
                                    .Where(ta => ta.ConfigurationTestId == testConfiguration.Id)
                                    .AsEnumerable()
                                    .Select(ta => new QuestionViewModel() {

                                        Id = ta.Id,
                                        Question = ta.Test.Question,
                                        QuestionType = ta.Test.QuestionTypeId,
                                        Answers = ta.Test.Answers.ToList().Select(a => new KeyValuePair<int, string>(a.Id, a.Description))

                                    })
                                    .First();

            return View("Question", primeraPregunta);

        }

        // POST: Tests/Siguiente/{AnswerId}/{AnswerText}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Siguiente(int AnswerId, string AnswerText) {

            // Se obtiene el nombre del usuaario
            var userName = User.Identity.Name;

            // Se cobtiene el la configuracion del Test del usuario
            var configTest = db.ConfigurationTest.First(c => c.Username.Equals(userName));

            // Se obtiene el registro de la pregunta que se ha respondido
            var testAnswer = db.TestAnswer.First(ta => ta.ConfigurationTestId == configTest.Id && ta.IsAnswered == false);

            // Se actualizan los campos
            testAnswer.AnwserIdSelected = AnswerId;
            testAnswer.IsAnswered = true;
            testAnswer.TextAnswer = AnswerText;

            // Se guardan los cambios en la BD
            db.Entry(testAnswer).State = EntityState.Modified;
            db.SaveChanges();

            // Se obtiene la siguiente pregunta
            var siguientePregunta = db.TestAnswer
                                    .Include(ta => ta.Test)
                                    .Where(ta => ta.ConfigurationTestId == configTest.Id && ta.IsAnswered == false)
                                    .AsEnumerable()
                                    .Select(ta => new QuestionViewModel() {

                                        Id = ta.Id,
                                        Question = ta.Test.Question,
                                        QuestionType = ta.Test.QuestionTypeId,
                                        Answers = ta.Test.Answers.ToList().Select(a => new KeyValuePair<int, string>(a.Id, a.Description))

                                    })
                                    .FirstOrDefault();

            ModelState.Clear();

            // Aun hay preguntas por responder
            if (siguientePregunta != null) {

                return View("Question", siguientePregunta);

            }

            return RedirectToAction("PruebaFinalizada");

        }

        public ActionResult PruebaFinalizada() {

            var userName = User.Identity.Name;

            // Se obtiene la configuración y las respuestas del test
            var configTest = db.ConfigurationTest
                               .Include(c => c.TestAnswer)
                               .FirstOrDefault(c => c.Username.Equals(userName));

            // Se obtienen los Id's de las respuestas cerradas constestadas
            var answersIdSelected = configTest.TestAnswer
                                              .Select(ta => ta.AnwserIdSelected)
                                              .ToList();

            // Se obtienen las respuestas
            var answers = db.Answer
                            .Where(a => answersIdSelected.Contains(a.Id))
                            .ToList();

            // Se cuentan las respuestas correctas
            var correctas = answers.Count(a => a.IsCorrect == true);

ForoIA/Views/Shared/_Comment.cshtml
@model ForoIA.Models.Db.Comment

<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading">
            @Html.ActionLink(Model.UserName, "UserPosts", "Posts", new { userName = Model.UserName }, null)
            <small>@Model.CommentTime</small>
        </h4>
        @Model.Content
    </div>
</div>

ForoIA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IA</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inteligencia Artificial en la ESIME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Online Test", "Index", "Tests")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Apuntes <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Chapter", "Multimedia", new { fileName = "IA1.pdf" })">Unidad I y II</a></li>
                            <li><a href="@Url.Action("Chapter", "Multimedia", new { fileName = "IA2.pdf" })">Unidad III, IV y V</a></li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Videos de interés", "Index", "Multimedia")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8" id="renderBody" role="main">
                <br />

                @RenderBody()
            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4" role="complementary">

                <br />

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Buscar en el Blog</h4>
                    @using (Html.BeginForm("Search", "Posts", FormMethod.Post)) {

                        @Html.AntiForgeryToken()

                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Búsqueda" name="param" id="param">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>

                    }
                    <!-- /.input-group -->
                </div>

                <!--Chat-->

                <div class="well">
                    <h4>Total de usuarios: @Html.Action("UserCount", "Account")</h4>
                    <p>Total de visitas: @(new Random().Next(1000, 9000))</p>
                </div>

            </div>

        </div>

        <!-- /.row -->
        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Inteligencia Artificial en la ESIME @DateTime.Now.Year</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ForoIA/Views/Shared/_Post.cshtml
@model ForoIA.Models.Db.Post

<!-- Blog Post -->
<!-- Title -->
<h1>@Model.Title</h1>

<!-- Author -->
<p class="lead">
    by @Html.ActionLink(Model.UserName, "UserPosts", "Posts", new { userName = Model.UserName }, null)
</p>

<hr>

<!-- Date/Time -->
<p><span class="glyphicon glyphicon-time"></span> Publicado @Model.Date en @Html.ActionLink(Model.Category.Name, "Category", "Posts", new { id = Model.CategoryId }, null)</p>
<hr>

<!-- Post Content -->
<p class="lead">@Model.Review</p>
<p>@Model.Content</p>

<hr>

<!-- Blog Comments -->
<!-- Comments Form -->
<div class="well">
    <h4>Deja tu comentario:</h4>
    @using (Html.BeginForm("Create", "Comments", FormMethod.Post)) {

        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Id)

        @Html.Hidden("userName", User.Identity.Name)

        @Html.ValidationSummary(false, null, new { @class = "text-danger" })

        @Html.ValidationMessage("identity")
        @Html.ValidationMessage("content")

        <div role="form">
            <div class="form-group">
                <textarea class="form-control" rows="3" name="content" placeholder="Comentar"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Comentar</button>
        </div>

    }

</div>

<hr />

@if (Model.Commments.Count > 0) {

    foreach (var commet in Model.Commments) {

        Html.RenderPartial("_Comment", commet);

    }

} else {

    <text>Aún no hay comentarios.</text>

}

ForoIA/Views/Shared/_PreviewPost.cshtml
@model ForoIA.Models.Db.Post

<!-- Blog Post -->
<h2>
    @Model.Title
</h2>

<p class="lead">
    por @Html.ActionLink(Model.UserName, "UserPosts", "Posts", new { userName = Model.UserName }, null)
</p>
<p><span class="glyphicon glyphicon-time"></span> Publicado @Model.Date en @Html.ActionLink(Model.Category.Name, "Category", "Posts", new { id = Model.CategoryId }, null)</p>
<hr>

@*<img class="img-responsive" src="http://placehold.it/900x300" alt="">
    <hr>*@

<p>@Model.Review</p>

<a class="btn btn-primary" href="@Url.Action("Details", "Posts", new { id = Model.Id })">
    Leer más <span class="glyphicon glyphicon-chevron-right"></span>
</a>

<hr />